# Generated by Django 5.2 on 2025-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
